### ISSUE TITLE
Please consider adding a link to tpch.coiled.io on the repos' description 

### ISSUE THREAD

**Issue by aimran-adroll** [coiled/tpch#6]
Might be helpful for lost souls like me 🙏🏽 

![image](https://github.com/coiled/tpch/assets/31903245/dcc757cb-d251-468e-8829-c84ee78b91ac)

**Comment by ntabris** [comment]
Thanks for the suggestion! There is now a link:

<img width="304" alt="image" src="https://github.com/coiled/tpch/assets/46289310/82088208-8ad7-4aa0-99a0-e5ce1aa66a0a">
